/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "scribe-docs"

pluginManagement {
    repositories {
        maven("https://maven.solo-studios.ca/releases")
        mavenCentral()
        gradlePluginPortal()
    }
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.jetbrains.dokka:versioning-plugin:1.7.20")
        classpath("org.jetbrains.dokka:dokka-core:1.7.20")
        classpath("org.jetbrains.dokka:dokka-base:1.7.20")
    }
}


include(
        "api",
        "cli",
        "frontend",
       )
